import { useEffect, useMemo, useState } from 'react';
import { createEstimate, getErrorMessage, getPublicConfig } from '../services/api';
import QuestionField from '../components/dynamic/QuestionField';

const blankContact = { name: '', phone: '', email: '' };
const currency = (amount, code = 'USD') => new Intl.NumberFormat('en-US', { style: 'currency', currency: code, maximumFractionDigits: 0 }).format(amount);

export default function Estimator() {
  const [config, setConfig] = useState(null); const [answers, setAnswers] = useState({}); const [contact, setContact] = useState(blankContact);
  const [step, setStep] = useState(0); const [errors, setErrors] = useState({}); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [requestError, setRequestError] = useState(''); const [estimate, setEstimate] = useState(null);
  useEffect(() => { getPublicConfig().then(setConfig).catch((err) => setRequestError(getErrorMessage(err, 'We could not load the estimator. Please refresh and try again.'))).finally(() => setLoading(false)); }, []);
  const questions = useMemo(() => (config?.questions || []).filter((question) => question.active), [config]); const contactStep = step === questions.length; const current = questions[step]; const total = questions.length + 1;
  const validate = () => {
    if (!contactStep) { const answer = answers[current.key]; let error = ''; if (current.required && (answer === undefined || answer === null || answer === '')) error = `${current.label} is required.`; if (answer !== '' && answer !== undefined && current.type === 'number') { if (Number.isNaN(Number(answer))) error = `${current.label} must be a number.`; if (current.min !== undefined && Number(answer) < current.min) error = `${current.label} must be at least ${current.min}.`; if (current.max !== undefined && Number(answer) > current.max) error = `${current.label} must be at most ${current.max}.`; } setErrors(error ? { [current.key]: error } : {}); return !error; }
    const next = {}; if (!contact.name.trim()) next.name = 'Please enter your name.'; if (!contact.phone.trim()) next.phone = 'Please enter a phone number.'; if (!contact.email.trim()) next.email = 'Please enter your email address.'; else if (!/^\S+@\S+\.\S+$/.test(contact.email)) next.email = 'Please enter a valid email address.'; setErrors(next); return !Object.keys(next).length;
  };
  const next = () => { if (validate()) setStep((value) => Math.min(value + 1, questions.length)); };
  const submit = async (event) => { event.preventDefault(); if (!validate()) return; setSubmitting(true); setRequestError(''); try { setEstimate(await createEstimate({ ...contact, answers })); } catch (err) { setRequestError(getErrorMessage(err, 'We could not calculate your estimate. Please try again.')); } finally { setSubmitting(false); } };
  const restart = () => { setAnswers({}); setContact(blankContact); setEstimate(null); setStep(0); setErrors({}); setRequestError(''); };
  if (loading) return <main className="page-shell centered-state"><div className="spinner" /><p>Preparing your estimator…</p></main>;
  if (!config) return <main className="page-shell centered-state"><h1>Estimator unavailable</h1><p>{requestError}</p><button className="button button-primary" onClick={() => window.location.reload()}>Try again</button></main>;
  if (estimate) return <Result config={config} estimate={estimate} restart={restart} />;
  return <main className="page-shell estimator-page"><header className="site-header"><a className="brand" href="/"><span className="brand-mark">N</span><span>{config.business.name}</span></a><span className="header-note">Free project estimate</span></header><section className="estimator-layout"><aside className="intro-panel"><p className="eyebrow">Northline Roofing & Exteriors</p><h1>A clearer start to your roofing project.</h1><p>Share a few project details and receive a personalized budget range in minutes.</p><div className="trust-list"><span>✓ No obligation</span><span>✓ Local, professional guidance</span><span>✓ Your details stay private</span></div></aside><section className="form-card" aria-live="polite"><div className="progress-head"><span>Step {step + 1} of {total}</span><span>{Math.round(((step + 1) / total) * 100)}% complete</span></div><div className="progress-track"><div style={{ width: `${((step + 1) / total) * 100}%` }} /></div><form onSubmit={submit}>{contactStep ? <Contact contact={contact} errors={errors} onChange={(key, value) => { setContact((old) => ({ ...old, [key]: value })); setErrors((old) => ({ ...old, [key]: '' })); }} /> : <><p className="eyebrow">Project details</p><h2>Tell us about your roof</h2><p className="form-description">This helps us prepare a more useful estimate for you.</p><QuestionField question={current} value={answers[current.key]} error={errors[current.key]} onChange={(key, value) => { setAnswers((old) => ({ ...old, [key]: value })); setErrors({}); }} /></>}{requestError && <p className="request-error" role="alert">{requestError}</p>}<div className="form-actions">{step > 0 && <button type="button" className="button button-secondary" onClick={() => { setStep((value) => value - 1); setErrors({}); }}>Back</button>}<button type={contactStep ? 'submit' : 'button'} className="button button-primary" onClick={contactStep ? undefined : next} disabled={submitting}>{submitting ? 'Calculating…' : contactStep ? 'Get my estimate' : 'Continue'} <span aria-hidden="true">→</span></button></div></form></section></section></main>;
}

function Contact({ contact, errors, onChange }) { return <><p className="eyebrow">Almost there</p><h2>Where should we send your estimate?</h2><p className="form-description">We’ll use these details only to follow up on your project.</p>{[['name', 'Name'], ['phone', 'Phone number'], ['email', 'Email address']].map(([key, label]) => <div className="question-field" key={key}><label htmlFor={key}>{label} <span aria-hidden="true">*</span></label><input id={key} type={key === 'email' ? 'email' : key === 'phone' ? 'tel' : 'text'} value={contact[key]} onChange={(event) => onChange(key, event.target.value)} autoComplete={key === 'name' ? 'name' : key === 'phone' ? 'tel' : 'email'} aria-invalid={Boolean(errors[key])} className={errors[key] ? 'has-error' : ''} />{errors[key] && <p className="field-error">{errors[key]}</p>}</div>)}</>;
}
function Result({ config, estimate, restart }) { return <main className="page-shell result-page"><header className="site-header"><a className="brand" href="/"><span className="brand-mark">N</span><span>{config.business.name}</span></a></header><section className="result-card"><div className="success-icon">✓</div><p className="eyebrow">Your estimated project range</p><h1>Thanks—we’ve got it.</h1><p className="form-description">Based on the details you shared, your preliminary estimate is:</p><p className="estimate-range">{currency(estimate.estimate_low, config.business.currency)} <span>–</span> {currency(estimate.estimate_high, config.business.currency)}</p><p className="result-note">This is a planning estimate, not a final quote. A Northline professional will confirm your project details and options with you.</p><button className="button button-secondary" onClick={restart}>Start another estimate</button></section></main>; }
